apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-csi-driver
  namespace: kube-system
  labels:
    application: kubernetes
    component: aws-mountpoint-s3-csi-driver
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
  annotations:
    iam.amazonaws.com/role: "{{ .Cluster.LocalID }}-s3-csi-driver"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: s3-csi-driver-privileged-psp
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
- kind: ServiceAccount
  name: s3-csi-driver
  namespace: kube-system
