apiVersion: v1
kind: Secret
metadata:
  name: skipper-ingress
  namespace: kube-system
  labels:
    application: skipper-ingress
type: Opaque
data:
  datadome-api-key: "{{ .Cluster.ConfigItems.datadome_api_key | base64 }}"
  kasada-api-key: "{{ .Cluster.ConfigItems.kasada_api_key | base64 }}"
  lightstep-token: "{{ .Cluster.ConfigItems.lightstep_token | base64 }}"
  encryption-key: "{{ .Cluster.ConfigItems.skipper_ingress_encryption_key | base64 }}"
  styra-token: "{{ .Cluster.ConfigItems.skipper_open_policy_agent_styra_token | base64 }}"