{{- if eq .Cluster.ConfigItems.config_provider_service "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-provider-service
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - business-partners-config
  - cfas-sales-channels-config
  verbs:
  - get
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: config-provider-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: config-provider-service
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: zalando-iam:zalando:service:stups_config-provider-service
{{- end }}
